### ISSUE TITLE
[Feature]  不同的wifi ssid下自动载入不同的配置文件

### ISSUE THREAD

**Issue by liangshixing** [MetaCubeX/ClashX.Meta#11]
感谢你向 ClashX 提交 Feature Request！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### 环境 Environment

* 使用者的操作系统 (the OS running on the client)
MacOS
* 网路环境或拓扑 (network conditions/topology)
Wifi
* iptables，如果适用 (if applicable)
无关
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
无关
* 其他
……

### 说明 Description

公司和家里分别要使用特殊配置，每次都要手动切换配置。建议能够根据SSID自动切换到不同的配置

### 可能的解决方案 Possible Solution

现在已经支持配置在特定的SSID下自动禁用，应该也能改造成切换配置文件

**Comment by mrFq1** [comment]
非meta 内核独有功能   请向上游ClashX 提交需求
