### ISSUE TITLE
[Feature]能否支持多个配置文件合并

### ISSUE THREAD

**Issue by lovelyyl** [MetaCubeX/ClashX.Meta#111]
感谢你向 ClashX 提交 Feature Request！
在提交之前，请确认：

- [ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的请求

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### 环境 Environment

* 使用者的操作系统 (the OS running on the client)
……
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

**Comment by FLIER001** [comment]
每个配置文件都有自己独立的分组、规则，及其命名，怎么合并？自己手动改改配置文件不就可以了吗

**Comment by lovelyyl** [comment]
你好，我的诉求是这样的。我有一个订阅链接，我自己也有一些转发的规则和一个转发节点。但我不想改动那个订阅的。因为订阅的偶尔会更新。我不知道怎么好一点处理他，我不想每次都手动同步那些规则。

**Comment by flyfanc** [comment]
> 你好，我的诉求是这样的。我有一个订阅链接，我自己也有一些转发的规则和一个转发节点。但我不想改动那个订阅的。因为订阅的偶尔会更新。我不知道怎么好一点处理他，我不想每次都手动同步那些规则。

你这种适合手搓规则，可以用proxy-providers订阅链接，使用rule-providers订阅规则，然后再加上自己的一些规则，这样可以自动更新订阅，也能有自己的一些规则。
参考：https://wiki.metacubex.one/example/conf/#__tabbed_1_2

**Comment by lovelyyl** [comment]
好的，谢谢答复。可能是我没太理解这些配置，我感觉有点复杂。我现在一直用脚本去解决这个问题。我期望的效果是，我可以本地建一个配置文件，然后通过诸如“extend”的配置，去继承一个配置文件，然后在我自己的配置里面做微小的改动。我的主程序就可以一直用我的本地配置。

**Comment by wangfpp** [comment]
@lovelyyl  你解决这个问题了吗  我也是需要一些自定义规则  更改配置文件是可以 但是配置文件更新后自定义规则就没了
