### ISSUE TITLE
[Bug]关于GEO文件

### ISSUE THREAD

**Issue by toyo2333** [MetaCubeX/ClashX.Meta#12]
请问安装包（程序包）内自带GEOip.dat 和GEOsite.dat么？ 还是说我得在配置文件里指定下载地址？

如果没有写。是不是rules里基于他们的规则就不生效了？
geosite,cn,direct 这样的

盼望答复。谢谢

**Comment by zzz6839** [comment]
@toyo2333 

硬气点

说话的方式硬气点

你礼貌的太表面

像没天赋的演员

观众一眼能看见




![image](https://github.com/MetaCubeX/ClashX.Meta/assets/57741549/47c8fdbf-73aa-4b2a-92b4-22a67ada0345)
