### ISSUE TITLE
[Bug] 类型为 tuic 的配置提示 token 为必须的 key，在使用 MetaClash 时正常

### ISSUE THREAD

**Issue by vkingw** [MetaCubeX/ClashX.Meta#14]
感谢你向 ClashX 提交 issue！
在提交之前，请确认：

- [ ✅] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [✅ ] 这是 ClashX UI层面的问题，并非 Clash Core 的问题(例如xx软件连不上，无法连接特定服务器等)。其他 Clash 衍生版本没有次问题。
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clashX config

```
 - name: go-tuic
    server: xxxx
    port: 1111
    type: tuic
    uuid: xxxx
    password: xxxx
    # ip: 127.0.0.1 # for overwriting the DNS lookup result of the server address set in option 'server'
    # heartbeat-interval: 10000
    alpn: [h3]
    disable-sni: true
    reduce-rtt: true
    request-timeout: 8000
    udp-relay-mode: native # Available: "native", "quic". Default: "native"
    # congestion-controller: bbr # Available: "cubic", "new_reno", "bbr". Default: "cubic"
    # max-udp-relay-packet-size: 1500
    # fast-open: true
    # skip-cert-verify: true
    # max-open-streams: 20 # default 100, too many open streams may hurt performance
    # sni: example.com
……
```

### ClashX log

```
Use tags: with_gvisor
06/23/2023, 17:17:06.443  [info] Start initial configuration in progress
06/23/2023, 17:17:06.444  [info] proxy 0: key 'token' missing
06/23/2023, 17:17:31.807  [info] Start initial configuration in progress
06/23/2023, 17:17:31.815  [info] Geodata Loader mode: standard
06/23/2023, 17:17:31.817  [warning] Deprecated: Use Sniff instead
06/23/2023, 17:17:31.817  [info] Initial configuration complete, total time: 10ms
06/23/2023, 17:17:31.817  [info] Sniffer is loaded and working
06/23/2023, 17:17:31.817  [info] Use tcp concurrent
06/23/2023, 17:17:31.817  [info] Use routing mark: 0x1a0a
……
```

### ClashX Crash log

```
……
```

### 环境 Environment
……
* 使用者的操作系统 (the OS running on the client)
* macOS :13.4.1 (22F82)
* 网路环境或拓扑 (network conditions/topology)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 重现问题的具体布骤 Steps to Reproduce

1. 添加使用 tuic 的 proxy
2. 使用 uuid 和 password 认证
3. 弹出窗口提示 “ proxy 0: key 'token' missing ”

**我预期会发生……？**

在使用 tuic 时，token是非必须的。这个在直接使用 Meta Clash 内核时同一份配置是正常

**实际上发生了什麽？**

提示配置缺少 token 这个key，加上 token 后 proxy 也是无法使用的

**Comment by kilvn** [comment]
用最新的 alpha meta 内核就好了

**Comment by vkingw** [comment]
> 用最新的 alpha meta 内核就好了

太好了，改用  alpha meta 就好了，十分感谢！
