### ISSUE TITLE
[Bug]API Connect Error

### ISSUE THREAD

**Issue by kilvn** [MetaCubeX/ClashX.Meta#15]
- [ ✅ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [ ] 这是 ClashX UI层面的问题，并非 Clash Core 的问题(例如xx软件连不上，无法连接特定服务器等)。其他 Clash 衍生版本没有次问题。
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

配置无问题，一直能用，这次无法启动了，未修改过配置文件

这个报错时不时会出现，相比 clashX 不是很稳定

![image](https://github.com/MetaCubeX/ClashX.Meta/assets/16423601/acaefe07-2da4-48f1-8c0f-3d3799d4af0c)

![image](https://github.com/MetaCubeX/ClashX.Meta/assets/16423601/b4ae3e47-7ecf-4d77-9cc2-d30e347f9745)

![image](https://github.com/MetaCubeX/ClashX.Meta/assets/16423601/0db80042-9ef8-441a-849d-8aeb2553de5b)

![image](https://github.com/MetaCubeX/ClashX.Meta/assets/16423601/e01fae9e-b47f-4138-a166-1b5027ac3b5e)

* 使用者的操作系统 (the OS running on the client)
MacOS 13.4.1

**Comment by Skyxim** [comment]
提示表明，配置文件出现配置或语法错误，导致内核无法启动，所以无法链接

**Comment by kilvn** [comment]
根本没动配置文件。。。。。重启了下电脑才好了。。。。。

**Comment by kilvn** [comment]
作者在TG群回复了

helper 总是莫名其妙抽搐  原因不明

为了能用tun 改成了helper 提权  然后NSTask 直接启动裸核

有空再研究  把报错再详细一点....

**Comment by imgwho** [comment]
> 

我重启了 mac 还是不行，大佬具体咋做的

**Comment by imgwho** [comment]
> 作者在TG群回复了
> 
> helper 总是莫名其妙抽搐 原因不明
> 
> 为了能用tun 改成了helper 提权 然后NSTask 直接启动裸核
> 
> 有空再研究 把报错再详细一点....


我重启了 mac 还是不行，大佬具体咋做的

**Comment by kilvn** [comment]
> 用tun 改成了helper 提权

平时偶尔报这个错重载配置文件就好了，昨天重启才好，还不行就不知道了
