### ISSUE TITLE
macOS 14 menu fixed in upstream

### ISSUE THREAD

**Issue by Dreamail** [MetaCubeX/ClashX.Meta#17]
Please update your code with upstream, which have fixed mac OS 14 crash on click menu icon.

**Comment by mrFq1** [comment]
Updated v1.2.7

**Comment by Dreamail** [comment]
it doesn't work at all

**Comment by xjbeta** [comment]
Did [ClashX 1.116.3](https://github.com/yichengchen/clashX/releases/tag/1.116.3) fix this bug?

**Comment by mrFq1** [comment]
Did [ClashX 1.116.3](https://github.com/yichengchen/clashX/releases/tag/1.116.3) fix this bug?

**Comment by Dreamail** [comment]
Yes, I think it is the Swift UI's problem. Yard dashboard version doesn't crash.

**Comment by mrFq1** [comment]
fixed v1.2.8
