### ISSUE TITLE
[Bug]运行应用后，菜单栏没有图标显示

### ISSUE THREAD

**Issue by yoohooyoo** [MetaCubeX/ClashX.Meta#19]
系统版本：macOS Ventura 13.0（Macbook Air M2）
软件版本：1.2.9（ClashX.Meta.SwiftUI.macOS.12.0+.zip 和 ClashX.Meta.zip都测试了）
异常现象：运行后，菜单栏没有出现图标。但是代理可用。证明其实是运行成功的。
尝试过删除后安装，重启等，均无效。

**Comment by yoohooyoo** [comment]
Mac系统问题，已经解决。关闭了。

**Comment by ningnnw** [comment]
是不是刘海遮挡了😂

**Comment by dadadong** [comment]
> Mac系统问题，已经解决。关闭了。

咋解决的...
