### ISSUE TITLE
[Bug]`chmodX` was missing in `updateAlphaMeta`

### ISSUE THREAD

**Issue by johntaiko** [MetaCubeX/ClashX.Meta#2]
This commit https://github.com/MetaCubeX/ClashX.Meta/commit/156bb4962be6b351dec114a6bdef7865df3beccd removed the chmodX from `testMetaCore`

But `updateAlphaMeta` needs `chmodX` after download new alpha core
https://github.com/MetaCubeX/ClashX.Meta/blob/156bb4962be6b351dec114a6bdef7865df3beccd/ClashX/AppDelegate.swift#L1302-L1387

**Comment by johntaiko** [comment]
It alerted with `Test downloaded file failed`

**Comment by mrFq1** [comment]
fixed 11496a8
