### ISSUE TITLE
[Bug]iOS stash 只能瀏覽器代理

### ISSUE THREAD

**Issue by aaron2wh** [MetaCubeX/ClashX.Meta#28]
因為找不到 iOS Stash的warp+ 支持在哪裡報錯，就找到這裡了。
我是使用 https://neko-warp.nloli.xyz/ 這個訂閱到Stash裡面。
但是發現在wifi環境下只能瀏覽器代理，YouTube，Facebook等應用還是無法打開，但是網頁版可以打開。
很奇怪，我用其他機場鏈接從來沒有這樣過。

**Comment by CHNJohnHK** [comment]
这关 clash 什么事

**Comment by aaron2wh** [comment]
對不起，我以為這個項目和 https://neko-warp.nloli.xyz/ 是同一個開發者，因為是我從那邊鏈接過來的
