### ISSUE TITLE
[Bug] MacOS 14读取存储在iCloud的配置文件

### ISSUE THREAD

**Issue by levinit** [MetaCubeX/ClashX.Meta#34]
### 环境 Environment
……
* 使用者的操作系统  MacOS14

### 问题

不能使用存储在icloud的配置文件，本地的~/.config/目录中的配置文件没有问题。

表现为：如果设置上勾选使用icloud存储配置文件，则点开clashX.meta图标后发现“出站模式”处不可选且显示有API error字样；使用本地的配置文件则正常，两个文件内容一致。

**Comment by yuzhi535** [comment]
我的也是，更新到 macos sonoma 出现了这个问题

**Comment by chmdir** [comment]
<img width="199" alt="截屏2023-09-30 19 59 47" src="https://github.com/MetaCubeX/ClashX.Meta/assets/64223803/7edd2143-7619-45e5-9d46-3edcaed19067">
同样

**Comment by WangAaron** [comment]
在macos sonoma系统设置--隐私与安全性--完全磁盘访问权限，给ClashX Meta开启权限即可访问iCloud的配置文件了，亲测有效。

**Comment by levinit** [comment]
> 在macos sonoma系统设置--隐私与安全性--完全磁盘访问权限，给ClashX Meta开启权限即可访问iCloud的配置文件了，亲测有效。

回去就试试，你这么一说应该是更新后一些授权失效了，有的程序也是，得删掉重新加。

**Comment by chmdir** [comment]
> > 在macos sonoma系统设置--隐私与安全性--完全磁盘访问权限，给ClashX Meta开启权限即可访问iCloud的配置文件了，亲测有效。
> 
> 回去就试试，你这么一说应该是更新后一些授权失效了，有的程序也是，得删掉重新加。

OK,解决了

**Comment by yee94** [comment]
我这里这么配置了还是有问题会是什么情况 🤦‍♂️

**Comment by birdmichael** [comment]
没有iCloud云盘权限

**Comment by zhiyuanzhai** [comment]
> 我这里这么配置了还是有问题会是什么情况 🤦‍♂️

@yee94 你需要确认配置两个app的权限，尤其是下面这个。

<img width="462" alt="image" src="https://github.com/user-attachments/assets/f079f916-358a-4d5c-a9c9-ca8edc1a5d07">

**Comment by tri5m** [comment]
打开com.metacubex.ClashX的完全磁盘访问权限就解决了。
