### ISSUE TITLE
[Bug]关于about信息问题

### ISSUE THREAD

**Issue by Apathy94** [MetaCubeX/ClashX.Meta#36]
![image](https://github.com/MetaCubeX/ClashX.Meta/assets/25723005/4f76137b-6a17-4a64-9c43-3a6a9a996e13)
下载了1.3.6版本，覆盖安装完毕之后，About窗口中显示版本是1.0（0）如图所示。

**Comment by tianzhuwei** [comment]
遇到同样的问题，已经退回1.3.5了，等官方修复/答复
