### ISSUE TITLE
[Bug] 1.3.6没有了切换内核的选项

### ISSUE THREAD

**Issue by skill7899** [MetaCubeX/ClashX.Meta#39]
感谢你向 ClashX 提交 issue！
在提交之前，请确认：

- [✓ ] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [✓ ] 这是 ClashX UI层面的问题，并非 Clash Core 的问题(例如xx软件连不上，无法连接特定服务器等)。其他 Clash 衍生版本没有次问题。
- [X ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clashX config

```
无
```

### ClashX log

```
无
```

### ClashX Crash log

```
无
```

### 环境 Environment
……
* 使用者的操作系统 (the OS running on the client)
M1 MACOS14.1
* 网路环境或拓扑 (network conditions/topology)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 说明 Description

1.3.5的版本
<img width="547" alt="image" src="https://github.com/MetaCubeX/ClashX.Meta/assets/13962272/a668a6a1-0585-455e-9261-41e86a69f9b9">
<img width="449" alt="image" src="https://github.com/MetaCubeX/ClashX.Meta/assets/13962272/fc2f1783-ce90-40e3-bf21-14f4db16236b">
控制台
<img width="1455" alt="image" src="https://github.com/MetaCubeX/ClashX.Meta/assets/13962272/0e332e72-5b94-4fdc-aa9f-310c0df88f3a">

1.3.6的版本

<img width="374" alt="image" src="https://github.com/MetaCubeX/ClashX.Meta/assets/13962272/6868accf-6e15-42f0-8613-5f9c645e3886">
<img width="440" alt="image" src="https://github.com/MetaCubeX/ClashX.Meta/assets/13962272/70930d0c-387b-474c-acae-4c4658c3d1e9">
控制吧
<img width="1464" alt="image" src="https://github.com/MetaCubeX/ClashX.Meta/assets/13962272/173323a9-0615-43fb-96ef-1d1ac193cd72">

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什麽？**

**Comment by gears233** [comment]
![SCR-20231103-lczr-2](https://github.com/MetaCubeX/ClashX.Meta/assets/57064324/b9917272-2c1f-4ae7-a3a4-bf9b97fe1724)

大概应该是整合到 settings 里面了

**Comment by skill7899** [comment]
> ![SCR-20231103-lczr-2](https://user-images.githubusercontent.com/57064324/280184734-b9917272-2c1f-4ae7-a3a4-bf9b97fe1724.png)
> 
> 大概应该是整合到 settings 里面了

1.3.7是不是启动不了

**Comment by gears233** [comment]
> 1.3.7是不是启动不了

刚更新后报了 connect error ； 重启后正常了
