### ISSUE TITLE
[Bug] ClashX.meta for mac 客户端打开控制台UI界面 javascript 错误页面加载空白

### ISSUE THREAD

**Issue by OrangeLazyCat** [MetaCubeX/ClashX.Meta#42]
问题描述：
ClashX.meta for mac 客户端打开控制台UI界面 javascript 错误页面加载空白

![1699622240993](https://github.com/MetaCubeX/ClashX.Meta/assets/54943553/ec4309c1-74af-41e9-a987-9c89c791f655)

**Comment by fireinrain** [comment]
这个界面我也出现过

**Comment by hyliang96** [comment]
我也出现过这种情况，我在macbook pro（MacOS 10.15.7，Intel）上测试了最近几个版本的clashX Meta，
clashX Meta v1.3.6~1.3.9会出现控制台UI界面空白，<=v1.3.5则不会出现。请问其他用户是否遇到类似情况？

**Comment by fireinrain** [comment]
> 我也出现过这种情况，我在macbook pro（MacOS 10.15.7，Intel）上测试了最近几个版本的clashX Meta， clashX Meta v1.3.6~1.3.9会出现控制台UI界面空白，<=v1.3.5则不会出现。请问其他用户是否遇到类似情况？

我就是因为这个问题 一直不敢升级clashx meta，1.3.5以上的都有这个问题
