### ISSUE TITLE
[Bug]API Connect Error

### ISSUE THREAD

**Issue by misakaok** [MetaCubeX/ClashX.Meta#51]
Sonoma 14.1.2 用的 1.3.7 版本 ClashX.Meta

**Comment by b1ghawk** [comment]
同样遇到，先降级看看。

**Comment by Ssiswent** [comment]
我也是
![image](https://github.com/MetaCubeX/ClashX.Meta/assets/37449310/a6f74ce6-0800-48a5-9320-bb0ac01e65a0)

**Comment by Ssiswent** [comment]
> 同样遇到，先降级看看。

请问降级就可以了吗

**Comment by b1ghawk** [comment]
> > 同样遇到，先降级看看。
> 
> 请问降级就可以了吗
> 

1.3.5没有这个问题。

**Comment by garipan** [comment]
解决方法：

下载1.3.5版本。不要下载"ClashX.Meta.macOS.12.0+.zip"，这个版本不是完整版，下载下来实际版本号是1.0。要下载第二个文件"[ClashX.Meta.zip](https://github.com/MetaCubeX/ClashX.Meta/releases/download/v1.3.5/ClashX.Meta.zip)"。覆盖安装，就好了。
并确认在设置中已关闭"使用iCloud托管配置文件"，这个也会导致加载失败。

**Comment by diduweiwu** [comment]
我这边也是类似的问题，但是我是启动时候要卡顿半天，概率性的报API Connect error。降级到1.3.5后，秒开 并且不会卡顿

**Comment by makaspacex** [comment]
> 解决方法：
> 
> 下载1.3.5版本。不要下载"ClashX.Meta.macOS.12.0+.zip"，这个版本不是完整版，下载下来实际版本号是1.0。要下载第二个文件"[ClashX.Meta.zip](https://github.com/MetaCubeX/ClashX.Meta/releases/download/v1.3.5/ClashX.Meta.zip)"。覆盖安装，就好了。 并确认在设置中已关闭"使用iCloud托管配置文件"，这个也会导致加载失败。

@garipan Sonoma 14.2 (23C64) 工作正常 感谢

**Comment by xflman** [comment]
ClashX.Meta.macOS.12.0+.zip
ClashX.Meta.zip
请问这两个版本的差别是啥呢？

**Comment by vvanglro** [comment]
> ClashX.Meta.macOS.12.0+.zip
> 
> ClashX.Meta.zip
> 
> 请问这两个版本的差别是啥呢？

同问，试了安装这两个版本，macos12的这个版本在更多设置里支持选择swiftui控制台，另一个版本的不支持，结果不支持的这个版本包的体积比支持的要大，没搞懂
