### ISSUE TITLE
ipv6配置无法启用

### ISSUE THREAD

**Issue by kilvn** [MetaCubeX/ClashX.Meta#59]
brew安装的1.3.9，都重启好几次了，一直灰色
<img width="486" alt="image" src="https://github.com/MetaCubeX/ClashX.Meta/assets/16423601/5952df2c-4ad7-44e8-8fa1-5483c464a4e2">

**Comment by vvanglro** [comment]
你好，能问下怎么解决的嘛，在对应的配置yaml文件里ipv6也设置成true了，这里还是灰色
