### ISSUE TITLE
[Bug] 系统休眠后，内存占用暴涨

### ISSUE THREAD

**Issue by binarrii** [MetaCubeX/ClashX.Meta#6]
**每天晚上系统休眠后，第二天再用时，显示内存使用量暴涨（见下图），正常情况下占用量就 40MB ~ 50MB**

### 环境
* macOS Monterey 12.6.5

![CXM20230508-133810](https://user-images.githubusercontent.com/8007836/236744459-98ffc47f-f6d5-4bdf-a96e-31a23ad9ba0c.png)

**Comment by mrFq1** [comment]
上游sing-tun 导致的流量回环

**Comment by mrFq1** [comment]
https://github.com/SagerNet/sing-tun/issues/9

**Comment by Skyxim** [comment]
大概是识别接口错误了，识别到 tun 自己，导致睡眠恢复后产生流量回环
