### ISSUE TITLE
[Bug]机场订阅链接提示托管配置文件格式不正确导致无法更新订阅链接,但是内容提示测试成功

### ISSUE THREAD

**Issue by KevinYouu** [MetaCubeX/ClashX.Meta#68]
感谢你向 ClashX 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 ClashX UI层面的问题，并非 Clash Core 的问题(例如xx软件连不上，无法连接特定服务器等)。其他 Clash 衍生版本没有次问题。
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### ClashX log

```
03/30/2024 12:43:10.933  [info] RemoteConfigManager.swift updateCheck(ignoreTimeLimit:showNotification:) [Auto Upgrade] Finish custom result: 托管配置文件格式不正确: configuration file /Users/Kevin/Library/Caches/com.MetaCubeX.ClashX.meta/cacheConfigs/AAE24B99-AD0D-428F-8F07-6E8A0DC7CAC7.yaml test is successful
```

### 重现问题的具体布骤 Steps to Reproduce

1. 添加托管配置
2. 添加机场订阅链接
3. 提示格式不正确, 但是内容提示验证成功
4. 无法新增订阅
5. 尝试了4个不同订阅链接都是同样的结果
6. 链接的订阅文件的内容直接粘贴保存可以成功加载
<img width="260" alt="截屏2024-03-30 12 45 02" src="https://github.com/MetaCubeX/ClashX.Meta/assets/46970005/e4f708db-e5fb-48d8-9bf4-086adf97ca40">
<img width="403" alt="截屏2024-03-30 12 56 19" src="https://github.com/MetaCubeX/ClashX.Meta/assets/46970005/fe3c0812-ed09-403b-9a12-eb73d2d2f0db">

**我预期会发生……？**

**实际上发生了什麽？**

### 可能的解决方案 Possible Solution
是否为订阅后的判断逻辑有误

**Comment by LiXin-x** [comment]
更新客户端到1.3.11/1.3.12 我也遇到一样的问题。

**Comment by LiXin-x** [comment]
顺便提一嘴，最近几个版本，控制台选择 metacubexd，无法滚动页面（懒得开 issue）

**Comment by hld1993413** [comment]
我也是，1.3.12有一样的问题

**Comment by jtzhpf** [comment]
同样的问题，但配置确定是好的，手动把配置文件从 ~/Library/Caches/com.MetaCubeX.ClashX.meta/cacheConfigs/ 目录下粘贴到配置文件目录下能正常运行

**Comment by ppttvs** [comment]
更新客户端到1.3.11/1.3.12，我也遇到一样的问题。

**Comment by fireinrain** [comment]
一模一样的问题 几个版本以前同一个订阅没问题，但是新的这几个版本 我试了一下 都是报错的
<img width="391" alt="image" src="https://github.com/MetaCubeX/ClashX.Meta/assets/14249262/75eb0f37-cbce-4250-8d48-38cb50b9b86c">

**Comment by coder-xb** [comment]
更新客户端到1.3.11/1.3.12，我也遇到了一样的问题，但我回退到1.3.10，就没问题了

**Comment by S1xOn6** [comment]
遇到一样的问题，回滚到 3.10 版本可以正常使用。3.11 和 3.12 都不行，打开就提示未找到 remote config yaml。在订阅里更新配置出现和楼上相同的报错

**Comment by abandon17** [comment]
加一，同样是回滚到3.10

**Comment by fireinrain** [comment]
可以确认是3.11 和3.12 有明确的问题，这么一看是改了实现方式导致的bug

**Comment by SliverYuki** [comment]
回退到 1.3.10 正常，等待新版本修复

**Comment by tony27786** [comment]
同样问题
