### ISSUE TITLE
ClashX.Meta 项目首页将“meta”分支调整为默认分支

### ISSUE THREAD

**Issue by TrayBer** [MetaCubeX/ClashX.Meta#76]
本项目当前默认分支是“master”，但是该分支项目信息为陈旧的，导致很多人打开当前页面，**以为项目已经停止维护了**。

关注、参与项目的人越多，越能推动项目的发展。

建议将 meta 分支调整为该项目首页展示。

**Comment by fireinrain** [comment]
关注的人越多不是死的越快吗， 内核都改成mihomo了 为了就是闷声发大财 ，懂的都懂

**Comment by TrayBer** [comment]
1.3.11 和 1.3.12 都存在明显的不能加载配置文件的 bug（大量用户提 issues），这个 bug 持续了 3 个月才最终在 1.3.13 版本得到修复。
是否维护人员太少、精力有限，才出现这样的状况。

仅对比同类项目：https://github.com/MetaCubeX/ClashMetaForAndroid ，差不多每1-2周就会发布一次更新（包含测试版），bug 修复速度快，能够做到及时跟进上游内核项目。

**Comment by RayvChan** [comment]
属于是根本没人维护吧，都是mihomo更新的了版本，这便是顺便编译的，编译后产生的bug基本不会修。
