### ISSUE TITLE
[Bug] Brew仓库又不维护了，还在 1.3.10

### ISSUE THREAD

**Issue by kilvn** [MetaCubeX/ClashX.Meta#79]
https://github.com/zuisong/homebrew-tap/blob/main/Casks/clashx-meta.rb

我都是通过brew更新软件的，辛苦作者了

**Comment by YannLau** [comment]
作者并没有在homebrew仓库上传本软件，你用的是第三方制作的tap的clashxmeta，你应该找这个tap的作者zuisong

**Comment by kilvn** [comment]
没注意作者，明白了~
